/** This file exists to suppress 'undefined reference' IDE warnings from Botland API calls.
 *  We could just disable all those warnings from IDE, but it's better to just supress this
 *  subset of warnings so the IDE can still warn us of actual undefined references. */

abs = function() {}
activateSensors = function() {}
areSensorsActivated = function() {}
canActivateSensors = function() {}
canCloak = function() {}
canEmp = function() {}
canMove = function() {}
canMoveTo = function() {}
canLayMine = function() {}
canReflect = function() {}
canShield = function() {}
canTeleport = function() {}
canZap = function() {}
ceil = function() {}
cloak = function() {}
debugLog = function() {}
distanceTo = function() {}
emp = function() {}
exists = function() {}
figureItOut = function() {}
filterEntities = function() {}
findClosestAlliedBot = function () {}
findClosestEnemyBot = function() {}
findEntities = function() {}
findEntitiesInRange = function() {}
findEntity = function() {}
fireArtillery = function() {}
fireLasers = function() {}
fireMissiles = function() {}
floor = function() {}
getDistanceTo = function() {}
getEntityAt = function() {}
getLife = function() {}
getX = function() {}
getY = function() {}
isCloaked = function() {}
isReflecting = function() {}
isZapping = function() {}
layMine = function() {}
max = function() {}
melee = function() {}
move = function() {}
pursue = function() {}
randInt = function() {}
reflect = function() {}
repair = function() {}
setAttackPriority = function() {}
size = function() {}
shield = function() {}
taunt = function() {}
teleport = function() {}
willMissilesHit = function() {}
willLasersHit = function() {}
willMeleeHit = function() {}
willArtilleryHit = function() {}
willRepair = function() {}
zap = function() {}


ENEMY = ""
BOT = ""
CHIP = ""
CPU = ""
IS_OWNED_BY_ME = ""
x = 0
y = 0
life = 0
ANYTHING = ""
SORT_BY_DISTANCE = ""
SORT_BY_LIFE = ""
SORT_ASCENDING = ""
SORT_DESCENDING = ""
arenaWidth = 0
arenaHeight = 0

BOT_CPU_CHIP = ""
BOT_CHIP_CPU = ""
CPU_BOT_CHIP = ""
CPU_CHIP_BOT = ""
CHIP_BOT_CPU = ""
CHIP_CPU_BOT = ""
